# Generated by Django 5.2.10 on 2026-01-27 12:54

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BugReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('steps_to_reproduce', models.TextField()),
                ('category', models.CharField(choices=[('ui', 'UI'), ('functionality', 'Functionality'), ('performance', 'Performance'), ('security', 'Security')], max_length=20)),
                ('severity', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('critical', 'Critical')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bug_reports', to='projects.project')),
                ('tester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_bugs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BugComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bug_reports.bugcomment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='bug_reports.bugreport')),
            ],
        ),
        migrations.CreateModel(
            name='BugAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('file_url', models.URLField(help_text='URL to file (e.g. Cloudinary)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('bug_report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='bug_reports.bugreport')),
            ],
        ),
    ]
