# Generated by Django 5.2.10 on 2026-01-24 16:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bug_reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bugcomment',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='bug_reports.bugcomment'),
        ),
    ]
