# Generated by Django 5.2.10 on 2026-02-01 14:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComplianceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=500)),
                ('readiness_score', models.IntegerField(default=0)),
                ('report_markdown', models.TextField()),
                ('tech_stack_raw', models.JSONField(blank=True, default=dict)),
                ('headers_raw', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('maintainer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compliance_audits', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
