# Generated by Django 5.2.10 on 2026-02-01 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compliance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complianceaudit',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='compliance_reports/'),
        ),
    ]
