# Generated by Django 5.2.10 on 2026-01-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresetotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
                ('purpose', models.CharField(choices=[('PASSWORD_RESET', 'Password Reset'), ('ACCOUNT_ACTIVATION', 'Account Activation')], default='PASSWORD_RESET', max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='PasswordResetOTP',
        ),
    ]
